---
- name: Ensure apt list directory exists
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755

- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes
